 export function getData(){
     return [
        {
            name : 'BLOODSHOT',
            rate : 0 ,
            description:'Bloodshot vốn là một cựu binh mang tên Ray Garrison. Không may hy sinh trong lúc ra trận, anh được tập đoàn RST hồi sinh với một thân phận và siêu năng lực hoàn toàn khác biệt. Bằng hàng triệu nanobot chạy trong huyết quản, Bloodshot giờ đây sở hữu siêu sức mạnh, tốc độ, sức bền và khả năng hồi phục thần tốc hơn cả Deadpool.',
            img: 'images/hanh-dong/1.jpg',
            genres: 'Hành Động',
            genresSlug:'hanh-dong',
            year: 2020,
            video:'https://www.youtube.com/embed/VT29VvmzPhI',
            view:0,
            sta:'hot'
        },
        {
            name : 'JOKER',
            rate: 0,
            description:'JOKER từ lâu đã là siêu ác nhân huyền thoại của điện ảnh thế giới. Nhưng có bao giờ bạn tự hỏi, Joker đến từ đâu và điều gì đã biến Joker trở thành biểu tượng tội lỗi của thành phố Gotham? JOKER sẽ là cái nhìn độc đáo về tên ác nhân khét tiếng của Vũ trụ DC – một câu chuyện gốc thấm nhuần, nhưng tách biệt rõ ràng với những truyền thuyết quen thuộc xoay quanh nhân vật mang đầy tính biểu tượng này.',
            img: 'images/hanh-dong/5.jpg',
            genres:'Hành Động',
            genresSlug:'hanh-dong',
            year: 2019,
            video: "https://www.youtube.com/embed/0rG8Gs3kp1k",
            view:0,
        },
        {
            name : 'Fast And Furious',
            rate: 0,
            description: 'Dom và Letty hiện đang đi hưởng tuần trăng mật. Brian cùng Mia đã quyết định từ giã sự nghiệp. Các thành viên còn lại của nhóm cũng đã được minh oan và dần trở về với cuộc sống bình thường. Nhưng một người phụ nữ bí ẩn (do nữ diễn viên đoạt giải Oscar Charlize Theron thủ vai) đã dẫn dụ Dom vào thế giới tội phạm mà anh dường như không thể thoát ra được và thậm chí phản bội lại cả những người thân thiết nhất, họ sẽ phải trải qua những thử thách cam go mà họ chưa từng đối mặt.',
            img: 'images/hanh-dong/2.jpg',
            genres:'Hành Động',
            genresSlug:'hanh-dong',
            year: 2019,
            video: "https://www.youtube.com/embed/kobpH3-6uvU",
            sta:'hot',
            view:0,
        },
         {
            name : 'Người Nhện',
            rate: 0,
            description:"mazing Spider-Man hay Siêu Nhện Tái Xuất có khá nhiều khác biệt so với các phần trước tập trung ở sự khác biệt ở tính cách của các nhân vật, Peter không còn là cậu bé nhút nhát mà khá nghịch ngợm, bên cạnh đó đạo diễn Marc Webb cũng mạnh dạn đưa ra thêm nhiều thay đổi về cốt truyện để Amazing Spider-Man thực sự mới lạ so với các phiên bản cũ.",
            img:'images/hanh-dong/3.jpg',
            genresSlug:'hanh-dong',
            genres:"Hành Động",
            year:2017,
            video:"https://www.youtube.com/embed/AxSnQ1XK2e4",
            view:0,
        },
        {
            name : 'Hai Phượng',
            rate: 0,
            description:'Hai Phượng là một bộ phim hành động Việt Nam do đạo diễn Lê Văn Kiệt thực hiện và Studio 68 cùng với NHV Entertainment sản xuất, do Lotte Entertainment Việt Nam phát hành',
            img: 'images/hanh-dong/4.jpg',
            genres:'Hành Động',
            genresSlug:'hanh-dong',
            year:2019,
            video: "https://www.youtube.com/embed/lTnrKA8EQ1M",
            view:0,
        },
        {
            name : "MILE 22",
            rate: 0,
            description:`Nhóm đặc biệt Ground Branch nhận được nhiệm vụ phải đưa một tình báo nước ngoài từ Đại sứ quán Mỹ tại Đông Nam Á đến một sân bay để về lại Mỹ - cách đó 22 dặm. Khó khăn ở đây chính là "kiện hàng" này cũng bị truy đuổi bởi một loạt lực lượng hoạt động trong "sáng" lẫn "tối".`,
            img:'images/hanh-dong/6.jpg',
            genres:'Hành Động',
            genresSlug:'hanh-dong',
            year: 2019,
            video:"https://www.youtube.com/embed/RkFyqPLXKsw",
            view:0,
        },
        {
            name : 'Siêu Sát Thủ',
            rate: 0,
            description: 'Một cựu chiến binh già về hưu làm sát thủ giết thuê với phong cách cổ điển. Trong một lần hành nghề tình cờ quen được một phụ nữ đơn chiếc đang nuôi một bà mẹ mất trí.',
            img:'images/hanh-dong/7.jpg',
            genres:'Hành Động',
            genresSlug:'hanh-dong',
            year: 2018,
            video: "https://www.youtube.com/embed/XiscvtyTIy4",
            view:0,
        },
        {
            name : 'SKYSCAPER',
            rate: 0,
            description:'Dwayne Johnson sẽ vào vai cựu quân nhân và cựu trưởng nhóm đặc nhiệm giải cứu của FBI Will Ford đầy dũng cảm. Không may trong một nhiệm vụ nguy hiểm, tai nạn khủng khiếp xảy đến với Will làm anh mất đi chân trái của mình. Kể từ đó, Will Ford từ bỏ công việc tại FBI và trở thành chuyên gia đánh giá an ninh cho các tòa nhà',
            img:'images/hanh-dong/8.jpg',
            genresSlug:'hanh-dong',
            genres:'Hành Động',
            year:2019,
            video: "https://www.youtube.com/embed/H6DVAbHfsLI",
            view:0,
        },
        {
            name : 'VENOM',
            rate: 0,
            description: 'Quái Vật Venom là một kẻ thù nguy hiểm và nặng ký của Người nhện trong loạt series của Marvel. Chàng phóng viên Eddie Brock (do Tom Hardy thủ vai) bí mật theo dõi âm mưu xấu xa của một tổ chức và đã không may mắn khi nhiễm phải loại cộng sinh trùng ngoài hành tinh (Symbiote) và từ đó đã không còn làm chủ bản thân về thể chất lẫn tinh thần. Điều này đã dần biến anh thành quái vật đen tối và nguy hiểm nhất chống lại người Nhện - Venom.',
            img:'images/hanh-dong/9.jpg',
            genresSlug:'hanh-dong',
            genres:'Hành Động',
            year:2019 ,
            video: '"https://www.youtube.com/embed/KAnaVlpVq_g"',
            view:0,
        }, {
            name : 'Ant-Man and the Wasp',
            rate: 0,
            description:'Sau trận nội chiến khốc liệt, Scott Lang – anh hùng Người Kiến với khả năng phóng to, thu nhỏ lại phải đối mặt với sự lựa chọn khó khăn trong cuộc sống đời thường: làm siêu anh hùng gánh vác những trách nhiệm nặng nề của thế giới hay làm một người cha có trách nhiệm.',
            img:'images/vien-tuong/1.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year:2019,
            video: "https://www.youtube.com/embed/haJzlp3WkUY",
            view:0,
        }, {
            name : 'Avatar 2',
            rate: 0,
            description:'Avatar 2 - phần tiếp theo của siêu phẩm khoa học viễn tưởng kể về người Navi trên hành tinh Pandora được nhào nặn bởi đạo diễn huyền thoại James Cameron. Tính đến nay, Avatar vẫn giữ kỷ lục phim có doanh thu lớn nhất mọi thời đại với số tiền lên tới 2,8 tỷ USD.',
            img:'images/vien-tuong/2.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year: 2017,
            video: "https://www.youtube.com/embed/qt-eYen2M70",
            view:0,
        }, {
            name : 'Đại Dịch Xác Sống',
            rate: 0,
            description:'What We Become là một bộ phim kinh dị do Mỹ sản xuất xoay quanh câu chuyện về cuộc chiến chống virus zombie của cô bé Gustav cùng với gia đình của mình. Trong phim cả thị trấn nhỏ của Gustav đã bị cách li hoàn toàn với bên ngoài và phải chịu kiểm soát của quân đội, nhưng sẻ không có chuyện gì xảy ra nếu như Gustav không tò mò quá mức và mang lại hậu quả thảm khốc cho gia đình mình. Liệu Gustav và gia đình của mình sẻ có kết quả như thế nào?',
            img:'images/vien-tuong/3.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year: 2018,
            video:"https://www.youtube.com/embed/NzUbgU4s12g",
            view:0,
        }, {
            name : 'Dr.Strange',
            rate: 0,
            description: 'DOCTOR STRANGE là câu chuyện về bác sĩ Giải Phẫu Thần Kinh tên Stephen Vincent Strange. Cuộc đời anh thay đổi từ sau một tai nạn xe hơi khủng khiếp. Sau tai nạn đó, Stephen nhận ra mình có những năng lực bí ẩn cũng như biết thêm về thế giới ma thuật huyền bí. Từ một vị bác sĩ bình thường, Stephen Strange dần nhận được nhiều siêu năng lực để cứu trái đất khỏi những tai họa.',
            img:'images/vien-tuong/4.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year:2019,
            video:"https://www.youtube.com/embed/PdZa654fRRM",
            sta:'hot',
            view:0,
        }, {
            name : 'Harry Poster',
            rate: 0,
            description:'Kết thúc phần 1 là khi nhóm bạn Harry Potter, Ron và Hermione quay trở lại trường Hogwarts để tìm và tiêu diệt Trường Sinh Linh Giá cuối cùng của Voldemort. Nhưng Voldemort đã phát hiện ra nhiệm vụ của họ, và trận chiến pháp thuật lớn nhất trong lịch sử đã diễn ra ở đây, nơi mà biết bao người ngã xuống, nơi mà tất cả các pháp sư dũng cảm sẵn sàng đánh đổi cuộc sống của mình để tiêu diệt tận cùng thế lực hắc ám. Giáo sư Dumbledore mặc dù đã mất từ tập 6, nhưng ở phần cuối ông vẫn đóng vai trò quan trọng trong việc dẫn đường chỉ lối cho Harry chiến đấu với phù thủy hắc ám mạnh nhất mọi thời đại...',
            img:'images/vien-tuong/5.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year: 2016,
            video:"https://www.youtube.com/embed/I2bW68NHP_w",
            view:0,
        },
        {
            name : 'Jumanji',
            rate: 0,
            description: 'Những đoạn bắt bẻ nhau đầy hài hước, tình huống bất ngờ đúng chất game. Cách thắt mở vấn đề hấp dẫn và thỏa mãn người xem. Dù là tình bạn, tình đồng đội hay tình yêu, mọi thứ đều được giải quyết tuyệt vời trong Jumanji: Welcome To The Jungle.',
            img:'images/vien-tuong/6.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year:2019,
            video:"https://www.youtube.com/embed/EjjMj32RCF0",
            view:0,
        },
        {
            name : 'Thor tận thế Ranarok',
            rate: 0,
            description:'Ở bên kia vũ trụ, Thor (Chris Hemsworth) phải bước vào một cuộc chiến đầy khốc liệt với đối thủ mà anh sẽ gặp là một đồng đội cũ đến từ biệt đội Avenger – Hulk. Cuộc tìm kiếm sự sống còn của Thor khiến anh phải chạy đua với thời gian để ngăn chặn Hela (Cate Blanchett) tiêu diệt cả thế giới anh đang sống cùng nền văn minh Asgard.',
            img:'images/vien-tuong/7.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year:2019,
            video:"https://www.youtube.com/embed/FYVIjbPtvj4",
            view:0,
        },
        {
            name : 'Skylin3s',
            rate: 0,
            description:'Phim bắt đầu bằng việc điều tra viên Mark Corley của cục cảnh sát Los Angeles đi bảo lãnh cho cậu con trai Trent 18 tuổi. Trên đường về nhà, ông bỗng phát hiện ra những quầng sáng màu xanh kỳ lạ đang phủ kín bầu trời. Và chỉ trong một chớp mắt, toàn bộ cư dân của thành phố đông đúc này đã bị hút vào một con tàu khổng lồ của người ngoài hành tinh. Hai cha con đã dẫn một nhóm những người sống sót chạy về phía bến thuyền. Và rồi khi Trent bị bắt đưa lên con tàu ác mộng đó, Mark đã phải dấn thân vào một hành trình vô cùng cam go để giải cứu con trai của mình và toàn bộ người còn lại.',
            img:'images/vien-tuong/8.jpg',
            genresSlug:'vien-tuong',
            genres:'Viễn Tưởng',
            year:2018,
            video:"https://www.youtube.com/embed/CP6Wn1VkUeU",
            view:0,
        },
        {
            name : 'Xứ Sở Phép Thuật',
            rate: 0,
            description: 'Với Alice Through The Looking Glass, cô bé Alice (Mia Wasikowska) sẽ trở lại Wonderland cũng như khám phá ra rằng, thế giới thần tiên này hiện đang gặp rất nhiều vấn đề khó giải quyết. Nhân vật Mad Hatter (Johnny Depp) bỗng trở nên độc ác hơn. Alice là người duy nhất có thể khiến mọi chuyện trở về như lúc ban đầu trước khi quá muộn.',
            img:'images/vien-tuong/9.jpg',
            genres:'Viễn Tưởng',
            year: 2018,
            video: "https://www.youtube.com/embed/eciNmEv-_vo",
            sta:'hot',
            view:0,
        },
        {
            name : 'Ác Quỷ Rừng Sâu',
            rate: 0,
            description: 'Baba Yaga: Ác Quỷ Rừng Sâu kể về một cặp vợ chồng trẻ đang tìm kiếm bảo mẫu để chăm sóc đứa con gái mới chào đời. Thế nhưng người được thuê về lại khiến cả đứa bé ấy và cậu con trai lớn Egor kinh sợ. Một ngày, Egor phát hiện người bảo mẫu và em gái mình biến mất một cách đầy bí ẩn.',
            img:'images/kinh-di/1.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2018,
            video: "https://www.youtube.com/embed/p_2TalkgVjk",
            view:0,
        },
        {
            name : 'Annabelle',
            rate: 0,
            description: 'Annabelle là câu chuyện về nguồn gốc của búp bê quỷ ám. Đi sâu vào bộ phim lần này Annabelle xuất hiện tại một gia đình vợ chồng trẻ. Món quà John tặng vợ mình nhân dịp sinh nhật và chuyển tói nhà mới chính là con búp bê Annabelle. Vào một đêm định mệnh, nhà của họ bị hai kẻ tâm thần đột nhập vào. Kể từ sau sự kiện kinh hoàng, nhiều hiện tượng kì quái bắt đầu xảy ra trong nhà và đều liên quan tới búp bê Annabelle…',
            img:'images/kinh-di/2.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2019,
            video: "https://www.youtube.com/embed/wikKLnJmOZ0",
            view:0,
        }, 
        {
            name : 'Đảo kinh hoàng',
            rate: 0,
            description:' phim kinh dị nổi tiếng của những năm 1970-1980, đây sẽ là câu chuyện về quý ngài Roarke và trợ lý Tatto, chào mừng các vị khách đến hòn đảo biệt lập của mình, và hứa hẹn 1 cuộc sống trong mơ. Câu chuyện về quý ngài Roarke và trợ lý Tatto, chào mừng các vị khách đến hòn đảo biệt lập của mình, và hứa hẹn 1 cuộc sống trong mơ.',
            img:'images/kinh-di/3.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2020,
            video: "https://www.youtube.com/embed/AtByq0Fbv9w",
            view:0,
        }, 
        {
            name : 'Ma Gương 2',
            rate: 0,
            description: 'Quyết tâm chứng minh sự vô tội của Tim, Kaylie truy tìm dấu vết của tấm gương, và khám phá ra rằng những cái chết tương tự như của cha mẹ họ đã xảy đến với những người chủ trước của tấm gương từ nhiều thế kỷ nay. Khi đã nắm trong tay thứ tạo vật kỳ bí này, cuộc sống thực tại của Tim và Kaylie bị khủng bố bởi những ảo giác kinh hoàng, và rồi họ muộn màng nhận ra rằng cơn ác mộng tuổi thơ lại bắt đầu...',
            img:'images/kinh-di/4.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2017,
            video: "https://www.youtube.com/embed/-Qe_prWQdBE",
            view:0,
        }, 
        {
            name : 'Nga Quỷ',
            rate: 0,
            description: 'Sidney và nhóm bạn của cô bị một tên sát nhân trong mặt nạt trằng đe doạ. Mọi nghi ngờ đổ về người yêu của cô. Cô nghĩ chuyện này có liên quan đến cái chết của mẹ cô cách đây một năm. Rồi từng người bạn của cô bị giết một cách bí ẩn',
            img:'images/kinh-di/5.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2016,
            video: "https://www.youtube.com/embed/50smxWE8L9Y",
            view:0,
        }, 
        {
            name : 'SCARY STORIES TO TELL IN THE DARK',
            rate: 0,
            description: 'Thời thế đang dần xoay chuyển nhưng dường như sự thay đổi ấy chẳng hề ảnh hưởng đến số đông cư dân ở thị trấn Mill Valley. Ở nơi đây, câu chuyện đầy ám ảnh về gia tộc Bellows vẫn được truyền miệng từ thế hệ này đến thế hệ khác. Khởi nguồn của những câu chuyện rùng rợn này bắt đầu từ căn biệt thự nằm ở vùng ven, trong căn nhà này cô bé Sarah Bellows đã phải chịu đựng một cuộc đời đau khổ, bị tra tấn bởi chính người thân trong gia đì',
            img:'images/kinh-di/6.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2018,
            video: "https://www.youtube.com/embed/jlFkMBPGp5c",
            view:0,
        },
         {
            name : 'Thang Máy',
            rate: 0,
            description: 'Sau khi bị lạc trong chuyến leo núi, một nhóm học sinh tình cờ phát hiện một ngôi nhà hoang chứa đựng những linh hồn lạc lối và một trò chơi chết người với bàn cờ.',
            img:'images/kinh-di/7.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2019,
            video:"https://www.youtube.com/embed/kbcduHeqMBM",
            view:0,
        },
         {
            name : 'Thì Nhiệm Xác Sống',
            rate: 0,
            description: 'Chín năm sau khi gần như toàn nhân loại bị nhiễm dịch bị biến thành các sinh vật dại (tựa như zombie), Patrick, Jack và Lu, một cô gái 9 tuổi, sống trong hòa bình và yên tĩnh ở thị trấn phủ đầy tuyết bị lãng quên của Harmony. Họ cảm thấy có gì khủng khiếp đã xảy ra giữa Patrick và Jack khiến họ ngày càng bị đẩy ra xa nhau. Khi những sinh vật dại tìm đến, Patrick và Jack sẽ phải bỏ lại đằng sau tất cả sự hận thù để bảo vệ người thần của mình.',
            img:'images/kinh-di/8.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2020,
            video: "https://www.youtube.com/embed/T0CcSIqW1OI" ,
            view:0,
        }, 
        {
            name : 'Trùng Quỷ Đại Dương',
            rate: 0,
            description: 'xoay quanh câu chuyện về hai cô gái người Mỹ đi nghỉ mát ở Mexico, bị mắc kẹt trong lồng quan sát cá mập dưới đáy đại dương. Cả hai phải tìm mọi cách để thoát hiểm trước những con cá mập trắng đang trực chờ nuốt chửng họ',
            img:'images/kinh-di/9.jpg',
            genresSlug:'kinh-di',
            genres:'Kinh Dị',
            year:2020,
            video: "https://www.youtube.com/embed/Dk1456TFMm4",
            view:0,
        },
        {
            name : 'Aladin',
            rate: 0,
            description: 'Aladdin 2019 là một phiên bản live action đầy màu sắc sống động và không kém phần hồi hộp, được chuyển thể từ bộ phim hoạt hình kinh điển cả hãng phim Disney. Câu chuyện xoay quanh chàng hoàng tử khu ổ chuột Aladdin – một thanh niên trẻ tuổi dũng cảm và nàng công chúa Jasmine mạnh mẽ, đương nhiên phải kể đến thần đèn Genie – người nắm giữ chìa khóa thay đổi tương lại sau này của họ.',
            img:'images/hoat-hinh/1.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year:2019,
            video: "https://www.youtube.com/embed/vPZGL1hXRrI",
            sta:'hot',
            view:0,
        },
        {
            name : 'Doramon & Nobita',
            rate: 0,
            description: 'Domreamon US xoay quanh vấn đề về anh bạn Nobita (Noby) và Doraemon, với những món bảo bối kì diệu, cùng các người bạn của Nobita như Xuka, Chaien (Big G), Xeko (Sneech),... Series này được phát hành bởi đài truyền hình Disney phiên bản Tiếng Anh, là bản hoàn toàn mới nhé.',
            img:'images/hoat-hinh/2.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year:2020,
            video: "https://www.youtube.com/embed/uZpLN4g7Qo",
            view:0,
        },
        {
            name : 'Lion King',
            rate: 0,
            description: 'Cuộc chiến ở Pride Rock trở nên khốc liệt hơn bao giờ hết và đỉnh điểm là việc chú sư tử Simba bị lưu đày khỏi quê hương. Với sự giúp đỡ của 2 người bạn mới Timon và Pumbaa, Simba dần học cách trưởng thành và quay trở về để giành lại những gì vốn dĩ thuộc về cậu. Bằng kĩ xảo đồ họa ấn tượng và âm nhạc sống động, Vua Sư Tử sẽ tái hiện lại những nhân vật mà khán giả yêu mến theo một cách hoàn toàn mới.',
            img:'images/hoat-hinh/3.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year:2019,
            video: "https://www.youtube.com/embed/eSw_zXYPLiU",
            view:0,
        },
        {
            name : 'Nhím Sonic',
            rate: 0,
            description: 'Chuyến phiêu lưu tới San Francisco của cảnh sát trưởng Tom Wachowski để hỗ trợ chú nhím xanh hình người Sonic chống lại bác sĩ Robotnik',
            img:'images/hoat-hinh/4.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year:2020,
            video: "https://www.youtube.com/embed/L4mKY2PcyfY",
            view:0,
        },
        {
            name : 'ONWARD',
            rate: 0,
            description:'Onward kể về cuộc phiêu lưu vô cùng thú vị để tìm kiếm các ma thuật còn sót lại trên thế giới của hai anh em yêu tinh Ian và Barley. Vốn mồ côi cha từ nhỏ, hai cậu thiếu niên luôn mang trong mình mong ước được gặp lại người cha quá cố và tin rằng phép thuật chính là chiếc chìa khoá thực hiện những ước mong của mình.',
            img:'images/hoat-hinh/5.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year:2019,
            video: "https://www.youtube.com/embed/kA60CpZY4JI",
            view:0,
        },
        {
            name : 'Scuby Doo',
            rate: 0,
            description: 'Chú chó Scooby và nhóm bạn đối mặt với một tên độc ác vô danh đeo mặt nạ đang khống chế thành phố Collsville bởi con quái vật máy được tạo ra bởi Tổng công ty Kỳ Bí như con ma khổng lồ, hiệp sỹ tàng hình, con ma điện... Dưới áp lực của nữ phóng viên Heather Jasper-Howe và những người dân xứ Coolvilles, nhóm bạn cùng hợp sức điều tra...',
            img:'images/hoat-hinh/6.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year:2019,
            video: "https://www.youtube.com/embed/0RafdzilidM",
            sta:'hot',
            view:0,
        },
        {
            name : 'Soul',
            rate: 0,
            description: 'Jamie Foxx vào vai Joe Gardner, một giáo viên trường trung học với một tình yêu mãnh liệt dành cho nhạc jazz. Tuy nhiên, Joe chưa kịp thực hiện được ước mơ của mình thì một tai nạn trớ trêu vô tình đã tách rời linh hồn và thể xác của ông. Linh hồn của Joe tỉnh dậy tại một trung tâm nơi những linh hồn khác đang rèn luyện chuẩn bị cho một kiếp người mới.',
            img:'images/hoat-hinh/7.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year:2020,
            video: "https://www.youtube.com/embed/x6uzY81Riyk",
            view:0,
        },
        {
            name : 'The Croods Poster',
            rate: 0,
            description: ' Eep là cô con gái lớn luôn tò mò về thế giới xung quanh. Mọi chuyện bỗng chốc thay đổi khi cô gặp Guy, một anh chàng hết sức thú vị với những phát minh lạ thường như lửa, dây nịt, giày … Và những thông tin anh chàng Guy mang tới đã đưa cả gia đình Croods vào một cuộc phiêu lưu mà họ không hề ngờ tới.',
            img:'images/hoat-hinh/8.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year: 2018,
            video: "https://www.youtube.com/embed/kA60CpZY4JI",
            view:0,
        },
        {
            name : 'Tom & Jerry',
            rate: 0,
            description: 'Câu chuyện bắt đầu vào một ngày trên bãi biển của Tom đôi co và Jerry ... cho đến khi họ đụng vào điệp viên đẳng cấp thế giới Jonny Quest và Hadji và chó cưng của họ Bandit. Khi gia đình lâu năm Quest nemesis TS Zin phát hiện ra rằng cha Jonny, tiến sĩ Benton Quest sở hữu một thiết bị có thể giải quyết vấn đề năng lượng của thế giới, Zin gửi quân đội mèo ác của mình để ăn cắp nó và nắm bắt Benton và vệ sĩ của ông. Đó là khi Jonny và bạn bè lông mới hành động ly kỳ và hồi hộp.',
            img:'images/hoat-hinh/9.jpg',
            genresSlug:'hoat-hinh',
            genres:'Hoạt Hình',
            year: 2019,
            video: "https://www.youtube.com/embed/QEL3nrSxyyw",
            view:0,
        },
       
        
        
    
    
    ]
    
 } 
